### PR TITLE
Fixed greedy/overreplacement of surrounding characters

### PR DESCRIPTION
**Pull request by SimeonC**
Have also added a logger for debugging to help assist anyone who wonders why their variables aren’t loaded.

The new regex for triggering the autocomplete is now much more specific as you can see here.
CleanShot 2022-05-11 at 12 38 31

Cases this should fix;

```
color: --;
        ^ cursor here and autocomplete triggered for `var(--black)`
// Current
color: var(--black)
// With this change (note the ; is not removed)
color: var(--black);
```

```
<p css={{ color: '--' }}
                    ^ cursor here and autocomplete triggered for `var(--black)`
// Current
<p css={{ color: ''var(--black)'' }}
// With this change (no excess quotes)
<p css={{ color: 'var(--black)' }}
```

### CODE REVIEW

**Comment by SimeonC** [comment]
@yeion7 I just updated this PR to also include a change so we can load CSS variables from compiled source code inside node_modules as well. The compiled code is often on one line like this;

```js
var lightColors = process.env.NODE_ENV === "production" ? {
  name: "fts42y",
  styles: "color-scheme:light;--border:rgba(229, 229, 229, 1);--border-active:rgba(41, 41, 41, 1);--border-transparent:rgba(0, 0, 0, 0.1);--error:rgba(204, 0, 0, 1);--error-surface:rgba(254, 223, 223, 1);--error-text:rgba(204, 0, 0, 1);--field:rgba(255, 255, 255, 1);--focus:rgba(0, 23, 231, 1);--info:rgba(0, 102, 204, 1);--info-surface:rgba(223, 239, 254, 1);--info-text:rgba(0, 102, 204, 1);--neutral-surface:rgba(249, 249, 249, 1);--neutral-text:rgba(75, 75, 75, 1);--secondary:rgba(41, 41, 41, 1);--secondary-active:rgba(75, 75, 75, 1);--secondary-hover:rgba(102, 102, 102, 1);--secondary-surface:rgba(249, 249, 249, 1);--success:rgba(6, 121, 0, 1);--success-surface:rgba(233, 254, 223, 1);--success-text:rgba(6, 121, 0, 1);--surface:rgba(255, 255, 255, 1);--surface-active:rgba(0, 0, 0, 0.14);--surface-alt:rgba(252, 252, 252, 1);--surface-alt-active:rgba(243, 242, 255, 1);--surface-alt-hover:rgba(249, 249, 249, 1);--surface-alt-hover-transparent:rgba(0, 0, 0, 0.03);--surface-disabled:rgba(229, 229, 229, 1);--surface-hover:rgba(238, 238, 238, 1);--surface-hover-transparent:rgba(0, 0, 0, 0.06);--text:rgba(41, 41, 41, 1);--text-contrast:rgba(255, 255, 255, 1);--text-disabled:rgba(206, 206, 206, 1);--text-placeholder:rgba(191, 191, 191, 1);--text-subtle:rgba(152, 152, 152, 1);--warning:rgba(232, 183, 47, 1);--warning-surface:rgba(255, 250, 223, 1);--warning-text:rgba(146, 107, 7, 1);--grey-950:rgba(30, 30, 30, 1);--grey-900:rgba(41, 41, 41, 1);--grey-850:rgba(58, 58, 58, 1);--grey-800:rgba(75, 75, 75, 1);--grey-750:rgba(102, 102, 102, 1);--grey-700:rgba(152, 152, 152, 1);--grey-600:rgba(191, 191, 191, 1);--grey-500:rgba(206, 206, 206, 1);--grey-400:rgba(219, 219, 219, 1);--grey-300:rgba(229, 229, 229, 1);--grey-200:rgba(238, 238, 238, 1);--grey-100:rgba(249, 249, 249, 1);--grey-50:rgba(253, 253, 253, 1)"
} : {
  name: "xb4y8r-lightColors",
  styles: "color-scheme:light;--border:rgba(229, 229, 229, 1);--border-active:rgba(41, 41, 41, 1);--border-transparent:rgba(0, 0, 0, 0.1);--error:rgba(204, 0, 0, 1);--error-surface:rgba(254, 223, 223, 1);--error-text:rgba(204, 0, 0, 1);--field:rgba(255, 255, 255, 1);--focus:rgba(0, 23, 231, 1);--info:rgba(0, 102, 204, 1);--info-surface:rgba(223, 239, 254, 1);--info-text:rgba(0, 102, 204, 1);--neutral-surface:rgba(249, 249, 249, 1);--neutral-text:rgba(75, 75, 75, 1);--secondary:rgba(41, 41, 41, 1);--secondary-active:rgba(75, 75, 75, 1);--secondary-hover:rgba(102, 102, 102, 1);--secondary-surface:rgba(249, 249, 249, 1);--success:rgba(6, 121, 0, 1);--success-surface:rgba(233, 254, 223, 1);--success-text:rgba(6, 121, 0, 1);--surface:rgba(255, 255, 255, 1);--surface-active:rgba(0, 0, 0, 0.14);--surface-alt:rgba(252, 252, 252, 1);--surface-alt-active:rgba(243, 242, 255, 1);--surface-alt-hover:rgba(249, 249, 249, 1);--surface-alt-hover-transparent:rgba(0, 0, 0, 0.03);--surface-disabled:rgba(229, 229, 229, 1);--surface-hover:rgba(238, 238, 238, 1);--surface-hover-transparent:rgba(0, 0, 0, 0.06);--text:rgba(41, 41, 41, 1);--text-contrast:rgba(255, 255, 255, 1);--text-disabled:rgba(206, 206, 206, 1);--text-placeholder:rgba(191, 191, 191, 1);--text-subtle:rgba(152, 152, 152, 1);--warning:rgba(232, 183, 47, 1);--warning-surface:rgba(255, 250, 223, 1);--warning-text:rgba(146, 107, 7, 1);--grey-950:rgba(30, 30, 30, 1);--grey-900:rgba(41, 41, 41, 1);--grey-850:rgba(58, 58, 58, 1);--grey-800:rgba(75, 75, 75, 1);--grey-750:rgba(102, 102, 102, 1);--grey-700:rgba(152, 152, 152, 1);--grey-600:rgba(191, 191, 191, 1);--grey-500:rgba(206, 206, 206, 1);--grey-400:rgba(219, 219, 219, 1);--grey-300:rgba(229, 229, 229, 1);--grey-200:rgba(238, 238, 238, 1);--grey-100:rgba(249, 249, 249, 1);--grey-50:rgba(253, 253, 253, 1);label:lightColors;",
  toString: _EMOTION_STRINGIFIED_CSS_ERROR__
};
```

**Comment by SimeonC** [comment]
@yeion7 Been a while, I eventually got back around to fixing some of the edge cases for this. It should be working much better now.

**Comment by yeion7** [comment]
@SimeonC sorry for review this one year later, all changes looks good, I'll publish a new version with this today

**Comment by yeion7** [comment]
Published `0.10.0`

**Comment by SimeonC** [comment]
Cool thanks! The new version looks good. It took me a year to get around to fixing a bug in the PR anyway!

**Pull request merged**
